version: '3'
services:
  # devcontainer:
  #   image: mcr.microsoft.com/devcontainers/universal:2
  #   volumes:
  #     - .:/workspace:cached

  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"

  fastapi:
    build: ../fastapi
    ports:
      - "8000:8000"
    depends_on:
      - tika

  react:
    build: ../.
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - fastapi