version: '3.9'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - .:/workspace:cached

  fastapi:
    profiles: [app]
    build: ../fastapi
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../fastapi/uploaded-files:/app/uploaded-files
        
  react:
    profiles: [app]
    build: ../.
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - fastapi